name: fitnessai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  step_progress_indicator: ^1.0.2
  numberpicker: ^2.1.2
  google_nav_bar: ^5.0.7
  lucide_icons: ^0.257.0
  table_calendar: ^3.2.0
  fl_chart: ^1.1.1
  http: ^1.6.0
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^12.0.1
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1   # <-- ADDED

# App icon config
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.jpg"

# Native splash config — shows solid black screen instantly on launch
# so there is NO white flash before your Dart SplashScreen appears
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png    # ← add your logo here
  fullscreen: true
  android_12:
    color: "#000000"               # ← this fixes Android 12+ default white screen
    image: assets/images/logo.png
    icon_background_color: "#000000"               # hides status bar during native splash

flutter:
  uses-material-design: true

  assets:
    - assets/images/